set(PROJECT Robot)
set(COMPONENT vision)
set(VERSION_MAJOR 0)
set(VERSION_MINOR 0)
set(VERSION_REVISON 0)

set(DESCRIPTION "Vision component for a robot.")
set(PROJECT_VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_REVISON})